# Generated by Django 5.1.6 on 2025-02-25 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0006_alter_user_phone_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(
                blank=True,
                help_text='Profile Picture',
                null=True,
                upload_to='profile_pictures/',
                validators=[django.core.validators.validate_image_file_extension],
                verbose_name='Profile Picture',
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
