# Generated by Django 5.1.6 on 2025-03-01 17:52

from django.db import migrations

import apps.user.models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0010_delete_profile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.user.models.CustomUserManager()),
            ],
        ),
    ]
