# Generated by Django 5.1.6 on 2025-03-04 07:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
        ('user', '0012_alter_user_email_alter_user_phone'),
    ]

    operations = []
