# Generated by Django 5.1.6 on 2025-02-25 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(
                blank=True,
                help_text='Phone Number',
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        '^\\d{7,10}$', message='Invalid phone number'
                    )
                ],
                verbose_name='phone_number',
            ),
        ),
    ]
