# Generated by Django 5.1.6 on 2025-02-25 10:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(
                blank=True,
                help_text='Phone Number',
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(7),
                    django.core.validators.MaxLengthValidator(10),
                ],
                verbose_name='Phone Number',
            ),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created_at', models.DateTimeField(auto_created=True, editable=False)),
                (
                    'first_name',
                    models.CharField(
                        blank=True,
                        help_text='First Name',
                        max_length=30,
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(50),
                            django.core.validators.MinLengthValidator(3),
                        ],
                        verbose_name='First Name',
                    ),
                ),
                (
                    'last_name',
                    models.CharField(
                        blank=True,
                        help_text='First Name',
                        max_length=50,
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(50),
                            django.core.validators.MinLengthValidator(3),
                        ],
                        verbose_name='Last Name',
                    ),
                ),
                (
                    'gender',
                    models.CharField(
                        choices=[
                            ('male', 'Male'),
                            ('female', 'Female'),
                            ('unknown', 'Unknown'),
                        ],
                        default='unknown',
                        help_text='Gender',
                        max_length=10,
                        verbose_name='Gender',
                    ),
                ),
                (
                    'bio',
                    models.TextField(
                        blank=True,
                        help_text='Bio',
                        max_length=100,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(1000)],
                        verbose_name='Bio',
                    ),
                ),
                (
                    'profile_picture',
                    models.FileField(
                        help_text='Profile Picture',
                        upload_to='profile_pictures/',
                        validators=[django.core.validators.validate_image_file_extension],
                        verbose_name='Profile Picture',
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        blank=True,
                        help_text='User',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='profile',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
