# Generated by Django 5.1.6 on 2025-03-01 17:52

import apps.account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_delete_profile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.account.models.CustomUserManager()),
            ],
        ),
    ]
