# Generated by Django 5.1.6 on 2025-03-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, editable=False, help_text='Verified status', verbose_name='Is Verified?'),
        ),
    ]
