# Generated by Django 5.1.6 on 2025-03-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('userprofile', '0002_profile_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='info',
            field=models.JSONField(
                blank=True,
                default=None,
                help_text='User information',
                null=True,
                verbose_name='Information',
            ),
        ),
    ]
