name: Django CI

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    env:
      SECRET_KEY: django-insecure-l07di_ji)%+7486q86^-eya9a7975j19)@imo5)!#1)lkh*pcg
      ALLOWED_HOSTS: localhost,127.0.0.1
      SQLITE_URL: sqlite///db.sqlite3
      CACHE_URL: pymemcache://127.0.0.1:11211,127.0.0.1:11212,127.0.0.1:11213

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
