name: Django CI

on:
  workflow_dispatch:
  push:
    branches: [ main, staging  ]
  pull_request:
    branches: [ main, staging ]

jobs:
  build:
    env:
      SECRET_KEY: django-insecure-l07di_ji)%+7486q86^-eya9a7975j19)@imo5)!#1)lkh*pcg
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
          python-version: ${{ matrix.python-version }}

    - name: Install the project
      run: uv sync --no-dev

    - name: Run tests
      run: uv run manage.py test
